#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -z 判断字符串是否为空 “”中可以有变量  ''中内容会原样输出
if [ -z "$ROCKETMQ_HOME" ]; then
  ## resolve links - $0 may be a link to maven's home
  # $0当前脚本的名称 包含路径
  PRG="$0"

  # need this for relative symlinks
  while [ -h "$PRG" ]; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' >/dev/null; then
      PRG="$link"
    else
      PRG="$(dirname "$PRG")/$link"
    fi
  done

  saveddir=$(pwd)

  ROCKETMQ_HOME=$(dirname "$PRG")/..

  # make it fully qualified
  ROCKETMQ_HOME=$(cd "$ROCKETMQ_HOME" && pwd)

  cd "$saveddir"
fi

export ROCKETMQ_HOME
# $@ 获取所有传递的参数 和$* 作用一致 但是a "b c" d $@将bc当成一个参数 $*是一个参数
# 类名后面的是程序参数 也就是main函数中的 args
sh ${ROCKETMQ_HOME}/bin/runserver.sh -Drmq.logback.configurationFile=$ROCKETMQ_HOME/conf/rmq.namesrv.logback.xml org.apache.rocketmq.namesrv.NamesrvStartup $@
